-- AlterTable
ALTER TABLE `Employer` ADD COLUMN `banned` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasImage` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `imageUrl` VARCHAR(191) NULL,
    ADD COLUMN `lastActiveAt` DATETIME(3) NULL,
    ADD COLUMN `lastSignInAt` DATETIME(3) NULL,
    ADD COLUMN `locked` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `User` ADD COLUMN `banned` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasImage` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `imageUrl` VARCHAR(191) NULL,
    ADD COLUMN `lastActiveAt` DATETIME(3) NULL,
    ADD COLUMN `lastSignInAt` DATETIME(3) NULL,
    ADD COLUMN `locked` BOOLEAN NOT NULL DEFAULT false;

-- AddForeignKey
ALTER TABLE `Order` ADD CONSTRAINT `Order_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
